jobs:
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - script: |
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run compile'
      - task: Npm@1
        displayName: 'Download Retina'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run download-retina'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: |
          export PATH=$PATH:$(pwd)/linux-x64
          echo "Let's go!"
          echo abc | Retina src/test/retina-scripts/hw.ret
          Retina src/test/retina-scripts/hw.ret
          node node_modules/vscode/bin/test
        displayName: 'Run tests'
        env:
          DISPLAY: :10
